name: Gosu-Catcher CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  S3_BUCKET_NAME: gosu-catcher-deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash

    - name: (Release) Get current date
      id: date
      run: echo "::set-output name=date::$(date+'%Y/%m/%d')"

    - name: Build with Gradle
      run: |
        ./gradlew -version
        ./gradlew build
      shell: bash
